# Generated by Django 4.0.2 on 2022-02-08 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppOne', '0003_alter_studentprofilemodel_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('message_status_read', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassModel',
            fields=[
                ('class_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('full_class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserClassExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentclassmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentMarksModel',
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppOne.userclassextension'),
        ),
    ]
