# Generated by Django 4.0.2 on 2022-02-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_messagesmodel_studentclassmodel_taskmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('student_id', models.ForeignKey(default='E', on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentprofilemodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.taskmodel')),
            ],
        ),
    ]
