# Generated by Django 4.0.2 on 2022-02-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0006_alter_studentprofilemodel_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentclassmodel'),
        ),
    ]
