# Generated by Django 4.0.2 on 2022-02-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0007_alter_studentprofilemodel_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentprofilemodel'),
        ),
    ]
