# Generated by Django 4.0.2 on 2022-07-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0008_alter_studentmarksmodel_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagesModel',
        ),
    ]
